### PR TITLE
Fixing incorrect stream closing/disposing

### LINKED ISSUE #160: Unusable in .NET Core
I am unable to get listing nor able to upload a file to a remote FTP server in a ASP.NET Core project. Tested 
the same piece of code in a .NET 4.6 project and it works. FileZilla also has no issues uploading files.

In the .NET Core project, a file is created on the remote server but no data is transferred.
capture

**Tested on the following workstations**
PC 1 and PC 2
OS: Windows 7 and Windows 10, respectively
FileZilla: 3.27.0.1
Firewall: Off
Visual Studio 2017
.NET Core: 1.1
FluentFTP: 17.6.1, also tested two previous versions

**Server**
Ubuntu: 16.04 LTS

**.NET Core**

    FtpTrace.LogToFile = "log.txt";
    FtpTrace.LogIP = false;
    FtpTrace.LogUserName = false;
    FtpTrace.LogPassword = false;

    FtpClient client = new FtpClient(HOST, USERNAME, PASSWORD);
    client.DataConnectionType = FtpDataConnectionType.AutoActive;
    client.DataConnectionEncryption = false;
    client.EncryptionMode = FtpEncryptionMode.None;
    client.Encoding = Encoding.UTF8;

    try
    {
        client.Connect();

        var list = client.GetListing("/");

        var data = Encoding.UTF8.GetBytes("Some data");
        client.Upload(data, "/test1.csv");
    }
    catch (Exception ex)
    {
    }

    if (client.IsConnected)
        client.Disconnect();

**Trace**
```

# Connect()
Status:   Connecting to ***:21
Response: 220 Please visit https://filezilla-project.org/
Response: 220-FileZilla Server 0.9.60 beta
Response: 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
Command:  USER ***
Response: 331 Password required for abcd
Command:  PASS ***
Response: 230 Logged on
Command:  FEAT
Response: 211 End
Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;
Response: MLSD
Response: UTF8
Response: CLNT
Response: MFMT
Response: EPSV
Response: EPRT
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 202 UTF8 mode is always enabled. No need to send this command.
Command:  SYST
Response: 215 UNIX emulated by FileZilla
Status:   Auto-detected UNIX listing parser

# GetListing("/", Auto)
Command:  TYPE I
Response: 200 Type set to I

# OpenActiveDataStream(AutoActive, "MLSD /", 0)
Command:  EPRT |1|10.0.0.32|50764|
Response: 200 Port command successful
Command:  MLSD /
Response: 150 Opening data channel for directory listing of "/"
+---------------------------------------+
-----------------------------------------
Status:   Disposing FtpSocketStream...

# Upload("/test1.csv", Overwrite, False)

# FileExists("/test1.csv")
Status:   There is stale data on the socket, maybe our connection timed out or you did not call GetReply(). Re-connecting...
Status:   The stale data was: 226 Successfully transferred "/"

# Connect()
Status:   Connecting to ***:21
Response: 220 Please visit https://filezilla-project.org/
Response: 220-FileZilla Server 0.9.60 beta
Response: 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
Command:  USER ***
Response: 331 Password required for abcd
Command:  PASS ***
Response: 230 Logged on
Command:  FEAT
Response: 211 End
Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;
Response: MLSD
Response: UTF8
Response: CLNT
Response: MFMT
Response: EPSV
Response: EPRT
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 202 UTF8 mode is always enabled. No need to send this command.
Command:  SYST
Response: 215 UNIX emulated by FileZilla
Status:   Auto-detected UNIX listing parser
Command:  SIZE /test1.csv
Response: 213 0

# DeleteFile("/test1.csv")
Command:  DELE /test1.csv
Response: 250 File deleted successfully

# OpenWrite("/test1.csv", Binary)
Command:  TYPE I
Response: 200 Type set to I

# GetFileSize("/test1.csv")
Command:  SIZE /test1.csv
Response: 550 File not found

# OpenActiveDataStream(AutoActive, "STOR /test1.csv", 0)
Command:  EPRT |1|10.0.0.32|50766|
Response: 200 Port command successful
Command:  STOR /test1.csv
Response: 150 Opening data channel for file upload to server of "/test1.csv"
Command:  QUIT
Response: 226 Successfully transferred "/test1.csv"

```

**.NET (4.6)**

    FtpTrace.LogIP = false;
    FtpTrace.LogUserName = false;
    FtpTrace.LogPassword = false;

    FtpClient client = new FtpClient(HOST, USERNAME, PASSWORD);
    client.DataConnectionType = FtpDataConnectionType.AutoActive;
    client.DataConnectionEncryption = false;
    client.EncryptionMode = FtpEncryptionMode.None;
    client.Encoding = Encoding.UTF8;

    try
    {
        client.Connect();

        var list = client.GetListing("/");

        var data = Encoding.UTF8.GetBytes("Some data");
        client.Upload(data, "/test.csv");

    }
    catch (Exception ex)
    {
    }

    if (client.IsConnected)
        client.Disconnect();

**Trace**

```# Connect()
Status:   Connecting to ***:21
Response: 220 Please visit https://filezilla-project.org/
Response: 220-FileZilla Server 0.9.60 beta
Response: 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
Command:  USER ***
Response: 331 Password required for abcd
Command:  PASS ***
Response: 230 Logged on
Command:  FEAT
Response: 211 End
Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;
Response: MLSD
Response: UTF8
Response: CLNT
Response: MFMT
Response: EPSV
Response: EPRT
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 202 UTF8 mode is always enabled. No need to send this command.
Command:  SYST
Response: 215 UNIX emulated by FileZilla
Status:   Auto-detected UNIX listing parser

# GetListing("/", Auto)
Command:  TYPE I
Response: 200 Type set to I

# OpenActiveDataStream(AutoActive, "MLSD /", 0)
Command:  EPRT |1|10.0.0.32|60090|
Response: 200 Port command successful
Command:  MLSD /
Response: 150 Opening data channel for directory listing of "/"
+---------------------------------------+
Listing:  type=dir;modify=20170809080806; Done
Listing:  type=dir;modify=20170809071909; Error
Listing:  type=dir;modify=20170809080801; Incoming
Listing:  type=dir;modify=20170809080806; Processing
Listing:  type=dir;modify=20170809075628; Response
-----------------------------------------

# CloseDataStream()
Response: 226 Successfully transferred "/"
Status:   Disposing FtpSocketStream...

# Upload("/test.csv", Overwrite, False)

# FileExists("/test.csv")
Command:  SIZE /test.csv
Response: 550 File not found

# OpenWrite("/test.csv", Binary)
Command:  TYPE I
Response: 200 Type set to I

# GetFileSize("/test.csv")
Command:  SIZE /test.csv
Response: 550 File not found

# OpenActiveDataStream(AutoActive, "STOR /test.csv", 0)
Command:  EPRT |1|10.0.0.32|60091|
Response: 200 Port command successful
Command:  STOR /test.csv
Response: 150 Opening data channel for file upload to server of "/test.csv"
Response: 226 Successfully transferred "/test.csv"
Command:  QUIT
Response: 221 Goodbye
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
```

### PR DESCRIPTION
**Pull request by artiomchi**
While working on the project testing, I stumbled upon a problem with some operations when running in .NET Standard. The library worked fine in .NET Framework, although it only did because it worked around the bug in the first place.

The .NET `Stream` class has three methods (relevant to this issue): `Close()`, `Dispose()` and `Dispose(bool)`. Both dispose methods are blank.  
`Dispose()` calls `Close()`  
`Close()` calls `Dispose(bool)`

The .NET Core's `Stream` class only has `Dispose()` and `Dispose(bool)`, both are blank.

To compensate for the missing `Close()`, the `FtpSocketStream` creates a new `Dispose()` method that calls `Close()`, overrides the `Close()` method (**not calling base.Close()**, and so not calling `Dispose(bool)`). For .NET Core, it creates a `Close()` method, and calls `Dispose()` inside. So we *already* have different paths in here.

In the `FtpDataStream` (derives from `FtpSocketStream`), the library overrides `Dispose(bool)` and **calls `Close()`**. This would actually cause the Close to call Dispose, but (un)luckily, the Close method doesn't call the base Close method, avoiding the circular call. This is the reason the error wasn't caught while running in .NET framework!

The main side-effect of this? In `FtpDataStream`'s `Dispose(bool)` method, we're clearing the `m_control` variable, without checking if the data stream has been properly cleared. In fact, just below, the `Close()` method checks if `m_control`'s property is not null, and if it's not, clears the control channel before nulling it.

If `Dispose(bool)` is called before `Close()` in this class, the library will never clear the data stream. That's exactly what happens when running under .NET core.
image

Fixes #160

### CODE REVIEW

File: FluentFTP/Stream/FtpSocketStream.cs [hunk 1]
```diff
@@ -740,10 +740,13 @@ public new void Dispose()
         /// Disconnects from server
         /// </summary>
 #if CORE
-		public void Close() {
+		public void Close()
+		{
+			base.Dispose(true);
```
Comment (artiomchi) [inline FluentFTP/Stream/FtpSocketStream.cs]: .NET Core, the new `Close()` method calls `Dispose(bool)`, same as in the .NET Framework

File: FluentFTP/Stream/FtpSocketStream.cs [hunk 2]
```diff
@@ -740,10 +740,13 @@ public new void Dispose()
...
 #else
         public override void Close()
         {
+            base.Close();
```
Comment (artiomchi) [inline FluentFTP/Stream/FtpSocketStream.cs]: Adding the missing call to the base `Close()` implementation when called in .NET Framework

File: FluentFTP/Stream/FtpSocketStream.cs [hunk 3]
```diff
@@ -809,10 +812,6 @@ public override void Close()
                 }
             }
 #endif
-
-#if CORE
-            base.Dispose();
```
Comment (artiomchi) [inline FluentFTP/Stream/FtpSocketStream.cs]: Removing incorrect call sequence, replaced with the call to `Dispose(bool)` above

File: FluentFTP/Stream/FtpDataStream.cs [hunk 4]
```diff
@@ -140,21 +140,6 @@ public class FtpDataStream : FtpSocketStream {
 		}
 
 		/// <summary>
-		/// Disconnects (if necessary) and releases associated resources
-		/// </summary>
-		/// <param name="disposing">Disposing</param>
-		protected override void Dispose(bool disposing) {
```
Comment (artiomchi) [inline FluentFTP/Stream/FtpDataStream.cs]: Removing the unnecessary override method. The `Close()` method should actually call this method instead, and `m_control` is cleared below in `Close()`

**Comment by artiomchi** [comment]
I just added the comments to add annotations to my changes, since I'm not sure who wrote the original method, and it would make peer reviewing it easier.

**Comment by robinrodricks** [comment]
Excellent work, as usual. Yes, I found the whole Close/Dispose methods so confusing that I just let it be the way it was instead of risking creating more bugs. Thank you for this fix.
